CREATE TABLE [dbo].[BoardAccess]
(
  [Id] INT NOT NULL PRIMARY KEY IDENTITY,
  [BoardId] INT NOT NULL,
  [UserId] UNIQUEIDENTIFIER NOT NULL,
  [CanEdit] BIT NOT NULL DEFAULT 0,
  [IsOwner] BIT NOT NULL DEFAULT 0,

  CONSTRAINT FK_BoardAccess_Board FOREIGN KEY (BoardId)
  REFERENCES dbo.Board (Id)
  ON DELETE CASCADE
)
